// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cycle.proto

package org.test.proto;

public final class CycleProto {
  private CycleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InnerBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InnerBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 value1 = 1;</code>
     */
    boolean hasValue1();
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    long getValue1();

    /**
     * <code>optional int64 value2 = 2;</code>
     */
    boolean hasValue2();
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    long getValue2();

    /**
     * <code>optional int64 value3 = 3 [default = 1000];</code>
     */
    boolean hasValue3();
    /**
     * <code>optional int64 value3 = 3 [default = 1000];</code>
     */
    long getValue3();

    /**
     * <code>optional int64 value4 = 4 [default = 1200];</code>
     */
    boolean hasValue4();
    /**
     * <code>optional int64 value4 = 4 [default = 1200];</code>
     */
    long getValue4();

    /**
     * <code>optional string value5 = 5;</code>
     */
    boolean hasValue5();
    /**
     * <code>optional string value5 = 5;</code>
     */
    java.lang.String getValue5();
    /**
     * <code>optional string value5 = 5;</code>
     */
    com.google.protobuf.ByteString
        getValue5Bytes();

    /**
     * <code>optional bytes value6 = 6;</code>
     */
    boolean hasValue6();
    /**
     * <code>optional bytes value6 = 6;</code>
     */
    com.google.protobuf.ByteString getValue6();

    /**
     * <code>optional .InnerBean reference = 7;</code>
     */
    boolean hasReference();
    /**
     * <code>optional .InnerBean reference = 7;</code>
     */
    org.test.proto.CycleProto.InnerBean getReference();
    /**
     * <code>optional .InnerBean reference = 7;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getReferenceOrBuilder();
  }
  /**
   * Protobuf type {@code InnerBean}
   */
  public  static final class InnerBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InnerBean)
      InnerBeanOrBuilder {
    // Use InnerBean.newBuilder() to construct.
    private InnerBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerBean() {
      value3_ = 1000L;
      value4_ = 1200L;
      value5_ = "";
      value6_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InnerBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              value1_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value2_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value3_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              value4_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value5_ = bs;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              value6_ = input.readBytes();
              break;
            }
            case 58: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = reference_.toBuilder();
              }
              reference_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reference_);
                reference_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.proto.CycleProto.internal_static_InnerBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.proto.CycleProto.internal_static_InnerBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.proto.CycleProto.InnerBean.class, org.test.proto.CycleProto.InnerBean.Builder.class);
    }

    private int bitField0_;
    public static final int VALUE1_FIELD_NUMBER = 1;
    private long value1_;
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    public boolean hasValue1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    public long getValue1() {
      return value1_;
    }

    public static final int VALUE2_FIELD_NUMBER = 2;
    private long value2_;
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    public boolean hasValue2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    public long getValue2() {
      return value2_;
    }

    public static final int VALUE3_FIELD_NUMBER = 3;
    private long value3_;
    /**
     * <code>optional int64 value3 = 3 [default = 1000];</code>
     */
    public boolean hasValue3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 value3 = 3 [default = 1000];</code>
     */
    public long getValue3() {
      return value3_;
    }

    public static final int VALUE4_FIELD_NUMBER = 4;
    private long value4_;
    /**
     * <code>optional int64 value4 = 4 [default = 1200];</code>
     */
    public boolean hasValue4() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 value4 = 4 [default = 1200];</code>
     */
    public long getValue4() {
      return value4_;
    }

    public static final int VALUE5_FIELD_NUMBER = 5;
    private volatile java.lang.Object value5_;
    /**
     * <code>optional string value5 = 5;</code>
     */
    public boolean hasValue5() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string value5 = 5;</code>
     */
    public java.lang.String getValue5() {
      java.lang.Object ref = value5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value5 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValue5Bytes() {
      java.lang.Object ref = value5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE6_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString value6_;
    /**
     * <code>optional bytes value6 = 6;</code>
     */
    public boolean hasValue6() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes value6 = 6;</code>
     */
    public com.google.protobuf.ByteString getValue6() {
      return value6_;
    }

    public static final int REFERENCE_FIELD_NUMBER = 7;
    private org.test.proto.CycleProto.InnerBean reference_;
    /**
     * <code>optional .InnerBean reference = 7;</code>
     */
    public boolean hasReference() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .InnerBean reference = 7;</code>
     */
    public org.test.proto.CycleProto.InnerBean getReference() {
      return reference_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : reference_;
    }
    /**
     * <code>optional .InnerBean reference = 7;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getReferenceOrBuilder() {
      return reference_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : reference_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, value3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, value4_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, value5_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, value6_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, getReference());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, value3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, value4_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, value5_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, value6_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getReference());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.test.proto.CycleProto.InnerBean)) {
        return super.equals(obj);
      }
      org.test.proto.CycleProto.InnerBean other = (org.test.proto.CycleProto.InnerBean) obj;

      boolean result = true;
      result = result && (hasValue1() == other.hasValue1());
      if (hasValue1()) {
        result = result && (getValue1()
            == other.getValue1());
      }
      result = result && (hasValue2() == other.hasValue2());
      if (hasValue2()) {
        result = result && (getValue2()
            == other.getValue2());
      }
      result = result && (hasValue3() == other.hasValue3());
      if (hasValue3()) {
        result = result && (getValue3()
            == other.getValue3());
      }
      result = result && (hasValue4() == other.hasValue4());
      if (hasValue4()) {
        result = result && (getValue4()
            == other.getValue4());
      }
      result = result && (hasValue5() == other.hasValue5());
      if (hasValue5()) {
        result = result && getValue5()
            .equals(other.getValue5());
      }
      result = result && (hasValue6() == other.hasValue6());
      if (hasValue6()) {
        result = result && getValue6()
            .equals(other.getValue6());
      }
      result = result && (hasReference() == other.hasReference());
      if (hasReference()) {
        result = result && getReference()
            .equals(other.getReference());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasValue1()) {
        hash = (37 * hash) + VALUE1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue1());
      }
      if (hasValue2()) {
        hash = (37 * hash) + VALUE2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue2());
      }
      if (hasValue3()) {
        hash = (37 * hash) + VALUE3_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue3());
      }
      if (hasValue4()) {
        hash = (37 * hash) + VALUE4_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue4());
      }
      if (hasValue5()) {
        hash = (37 * hash) + VALUE5_FIELD_NUMBER;
        hash = (53 * hash) + getValue5().hashCode();
      }
      if (hasValue6()) {
        hash = (37 * hash) + VALUE6_FIELD_NUMBER;
        hash = (53 * hash) + getValue6().hashCode();
      }
      if (hasReference()) {
        hash = (37 * hash) + REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getReference().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.test.proto.CycleProto.InnerBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.test.proto.CycleProto.InnerBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InnerBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InnerBean)
        org.test.proto.CycleProto.InnerBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.proto.CycleProto.internal_static_InnerBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.proto.CycleProto.internal_static_InnerBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.proto.CycleProto.InnerBean.class, org.test.proto.CycleProto.InnerBean.Builder.class);
      }

      // Construct using org.test.proto.CycleProto.InnerBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReferenceFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        value1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        value2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        value3_ = 1000L;
        bitField0_ = (bitField0_ & ~0x00000004);
        value4_ = 1200L;
        bitField0_ = (bitField0_ & ~0x00000008);
        value5_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        value6_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (referenceBuilder_ == null) {
          reference_ = null;
        } else {
          referenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.proto.CycleProto.internal_static_InnerBean_descriptor;
      }

      public org.test.proto.CycleProto.InnerBean getDefaultInstanceForType() {
        return org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      }

      public org.test.proto.CycleProto.InnerBean build() {
        org.test.proto.CycleProto.InnerBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.proto.CycleProto.InnerBean buildPartial() {
        org.test.proto.CycleProto.InnerBean result = new org.test.proto.CycleProto.InnerBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.value1_ = value1_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.value2_ = value2_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          result.value3_ = value3_;
          to_bitField0_ |= 0x00000004;
        } else {
          result.value3_ = 1000L;
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          result.value4_ = value4_;
          to_bitField0_ |= 0x00000008;
        } else {
          result.value4_ = 1200L;
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          result.value5_ = value5_;
          to_bitField0_ |= 0x00000010;
        } else {
          result.value5_ = "";
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          result.value6_ = value6_;
          to_bitField0_ |= 0x00000020;
        } else {
          result.value6_ = com.google.protobuf.ByteString.EMPTY;
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          if (referenceBuilder_ == null) {
            result.reference_ = reference_;
          } else {
            result.reference_ = referenceBuilder_.build();
          }
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.proto.CycleProto.InnerBean) {
          return mergeFrom((org.test.proto.CycleProto.InnerBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.proto.CycleProto.InnerBean other) {
        if (other == org.test.proto.CycleProto.InnerBean.getDefaultInstance()) return this;
        if (other.hasValue1()) {
          setValue1(other.getValue1());
        }
        if (other.hasValue2()) {
          setValue2(other.getValue2());
        }
        if (other.hasValue3()) {
          setValue3(other.getValue3());
        }
        if (other.hasValue4()) {
          setValue4(other.getValue4());
        }
        if (other.hasValue5()) {
          bitField0_ |= 0x00000010;
          value5_ = other.value5_;
          onChanged();
        }
        if (other.hasValue6()) {
          setValue6(other.getValue6());
        }
        if (other.hasReference()) {
          mergeReference(other.getReference());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.proto.CycleProto.InnerBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.proto.CycleProto.InnerBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long value1_ ;
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public boolean hasValue1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public long getValue1() {
        return value1_;
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public Builder setValue1(long value) {
        bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public Builder clearValue1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value1_ = 0L;
        onChanged();
        return this;
      }

      private long value2_ ;
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public boolean hasValue2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public long getValue2() {
        return value2_;
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder setValue2(long value) {
        bitField0_ |= 0x00000002;
        value2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder clearValue2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value2_ = 0L;
        onChanged();
        return this;
      }

      private long value3_ = 1000L;
      /**
       * <code>optional int64 value3 = 3 [default = 1000];</code>
       */
      public boolean hasValue3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 value3 = 3 [default = 1000];</code>
       */
      public long getValue3() {
        return value3_;
      }
      /**
       * <code>optional int64 value3 = 3 [default = 1000];</code>
       */
      public Builder setValue3(long value) {
        bitField0_ |= 0x00000004;
        value3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value3 = 3 [default = 1000];</code>
       */
      public Builder clearValue3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value3_ = 1000L;
        onChanged();
        return this;
      }

      private long value4_ = 1200L;
      /**
       * <code>optional int64 value4 = 4 [default = 1200];</code>
       */
      public boolean hasValue4() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 value4 = 4 [default = 1200];</code>
       */
      public long getValue4() {
        return value4_;
      }
      /**
       * <code>optional int64 value4 = 4 [default = 1200];</code>
       */
      public Builder setValue4(long value) {
        bitField0_ |= 0x00000008;
        value4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value4 = 4 [default = 1200];</code>
       */
      public Builder clearValue4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value4_ = 1200L;
        onChanged();
        return this;
      }

      private java.lang.Object value5_ = "";
      /**
       * <code>optional string value5 = 5;</code>
       */
      public boolean hasValue5() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public java.lang.String getValue5() {
        java.lang.Object ref = value5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value5_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValue5Bytes() {
        java.lang.Object ref = value5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public Builder setValue5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public Builder clearValue5() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value5_ = getDefaultInstance().getValue5();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public Builder setValue5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value5_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value6_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value6 = 6;</code>
       */
      public boolean hasValue6() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes value6 = 6;</code>
       */
      public com.google.protobuf.ByteString getValue6() {
        return value6_;
      }
      /**
       * <code>optional bytes value6 = 6;</code>
       */
      public Builder setValue6(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        value6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value6 = 6;</code>
       */
      public Builder clearValue6() {
        bitField0_ = (bitField0_ & ~0x00000020);
        value6_ = getDefaultInstance().getValue6();
        onChanged();
        return this;
      }

      private org.test.proto.CycleProto.InnerBean reference_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> referenceBuilder_;
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public boolean hasReference() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public org.test.proto.CycleProto.InnerBean getReference() {
        if (referenceBuilder_ == null) {
          return reference_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : reference_;
        } else {
          return referenceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public Builder setReference(org.test.proto.CycleProto.InnerBean value) {
        if (referenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reference_ = value;
          onChanged();
        } else {
          referenceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public Builder setReference(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (referenceBuilder_ == null) {
          reference_ = builderForValue.build();
          onChanged();
        } else {
          referenceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public Builder mergeReference(org.test.proto.CycleProto.InnerBean value) {
        if (referenceBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              reference_ != null &&
              reference_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            reference_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(reference_).mergeFrom(value).buildPartial();
          } else {
            reference_ = value;
          }
          onChanged();
        } else {
          referenceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public Builder clearReference() {
        if (referenceBuilder_ == null) {
          reference_ = null;
          onChanged();
        } else {
          referenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getReferenceBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getReferenceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getReferenceOrBuilder() {
        if (referenceBuilder_ != null) {
          return referenceBuilder_.getMessageOrBuilder();
        } else {
          return reference_ == null ?
              org.test.proto.CycleProto.InnerBean.getDefaultInstance() : reference_;
        }
      }
      /**
       * <code>optional .InnerBean reference = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getReferenceFieldBuilder() {
        if (referenceBuilder_ == null) {
          referenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getReference(),
                  getParentForChildren(),
                  isClean());
          reference_ = null;
        }
        return referenceBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InnerBean)
    }

    // @@protoc_insertion_point(class_scope:InnerBean)
    private static final org.test.proto.CycleProto.InnerBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.test.proto.CycleProto.InnerBean();
    }

    public static org.test.proto.CycleProto.InnerBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InnerBean>
        PARSER = new com.google.protobuf.AbstractParser<InnerBean>() {
      public InnerBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InnerBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InnerBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InnerBean> getParserForType() {
      return PARSER;
    }

    public org.test.proto.CycleProto.InnerBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OuterBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OuterBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .InnerBean bean1 = 1;</code>
     */
    boolean hasBean1();
    /**
     * <code>optional .InnerBean bean1 = 1;</code>
     */
    org.test.proto.CycleProto.InnerBean getBean1();
    /**
     * <code>optional .InnerBean bean1 = 1;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getBean1OrBuilder();

    /**
     * <code>optional .InnerBean bean2 = 2;</code>
     */
    boolean hasBean2();
    /**
     * <code>optional .InnerBean bean2 = 2;</code>
     */
    org.test.proto.CycleProto.InnerBean getBean2();
    /**
     * <code>optional .InnerBean bean2 = 2;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getBean2OrBuilder();

    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    java.util.List<org.test.proto.CycleProto.InnerBean> 
        getBeansList();
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    org.test.proto.CycleProto.InnerBean getBeans(int index);
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    int getBeansCount();
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    java.util.List<? extends org.test.proto.CycleProto.InnerBeanOrBuilder> 
        getBeansOrBuilderList();
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getBeansOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code OuterBean}
   */
  public  static final class OuterBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OuterBean)
      OuterBeanOrBuilder {
    // Use OuterBean.newBuilder() to construct.
    private OuterBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OuterBean() {
      beans_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OuterBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = bean1_.toBuilder();
              }
              bean1_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bean1_);
                bean1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = bean2_.toBuilder();
              }
              bean2_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bean2_);
                bean2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                beans_ = new java.util.ArrayList<org.test.proto.CycleProto.InnerBean>();
                mutable_bitField0_ |= 0x00000004;
              }
              beans_.add(
                  input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          beans_ = java.util.Collections.unmodifiableList(beans_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.proto.CycleProto.internal_static_OuterBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.proto.CycleProto.internal_static_OuterBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.proto.CycleProto.OuterBean.class, org.test.proto.CycleProto.OuterBean.Builder.class);
    }

    private int bitField0_;
    public static final int BEAN1_FIELD_NUMBER = 1;
    private org.test.proto.CycleProto.InnerBean bean1_;
    /**
     * <code>optional .InnerBean bean1 = 1;</code>
     */
    public boolean hasBean1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .InnerBean bean1 = 1;</code>
     */
    public org.test.proto.CycleProto.InnerBean getBean1() {
      return bean1_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean1_;
    }
    /**
     * <code>optional .InnerBean bean1 = 1;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getBean1OrBuilder() {
      return bean1_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean1_;
    }

    public static final int BEAN2_FIELD_NUMBER = 2;
    private org.test.proto.CycleProto.InnerBean bean2_;
    /**
     * <code>optional .InnerBean bean2 = 2;</code>
     */
    public boolean hasBean2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .InnerBean bean2 = 2;</code>
     */
    public org.test.proto.CycleProto.InnerBean getBean2() {
      return bean2_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean2_;
    }
    /**
     * <code>optional .InnerBean bean2 = 2;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getBean2OrBuilder() {
      return bean2_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean2_;
    }

    public static final int BEANS_FIELD_NUMBER = 3;
    private java.util.List<org.test.proto.CycleProto.InnerBean> beans_;
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    public java.util.List<org.test.proto.CycleProto.InnerBean> getBeansList() {
      return beans_;
    }
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    public java.util.List<? extends org.test.proto.CycleProto.InnerBeanOrBuilder> 
        getBeansOrBuilderList() {
      return beans_;
    }
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    public int getBeansCount() {
      return beans_.size();
    }
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    public org.test.proto.CycleProto.InnerBean getBeans(int index) {
      return beans_.get(index);
    }
    /**
     * <code>repeated .InnerBean beans = 3;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getBeansOrBuilder(
        int index) {
      return beans_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getBean1());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getBean2());
      }
      for (int i = 0; i < beans_.size(); i++) {
        output.writeMessage(3, beans_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBean1());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBean2());
      }
      for (int i = 0; i < beans_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, beans_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.test.proto.CycleProto.OuterBean)) {
        return super.equals(obj);
      }
      org.test.proto.CycleProto.OuterBean other = (org.test.proto.CycleProto.OuterBean) obj;

      boolean result = true;
      result = result && (hasBean1() == other.hasBean1());
      if (hasBean1()) {
        result = result && getBean1()
            .equals(other.getBean1());
      }
      result = result && (hasBean2() == other.hasBean2());
      if (hasBean2()) {
        result = result && getBean2()
            .equals(other.getBean2());
      }
      result = result && getBeansList()
          .equals(other.getBeansList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBean1()) {
        hash = (37 * hash) + BEAN1_FIELD_NUMBER;
        hash = (53 * hash) + getBean1().hashCode();
      }
      if (hasBean2()) {
        hash = (37 * hash) + BEAN2_FIELD_NUMBER;
        hash = (53 * hash) + getBean2().hashCode();
      }
      if (getBeansCount() > 0) {
        hash = (37 * hash) + BEANS_FIELD_NUMBER;
        hash = (53 * hash) + getBeansList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.test.proto.CycleProto.OuterBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.test.proto.CycleProto.OuterBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OuterBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OuterBean)
        org.test.proto.CycleProto.OuterBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.proto.CycleProto.internal_static_OuterBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.proto.CycleProto.internal_static_OuterBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.proto.CycleProto.OuterBean.class, org.test.proto.CycleProto.OuterBean.Builder.class);
      }

      // Construct using org.test.proto.CycleProto.OuterBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBean1FieldBuilder();
          getBean2FieldBuilder();
          getBeansFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (bean1Builder_ == null) {
          bean1_ = null;
        } else {
          bean1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bean2Builder_ == null) {
          bean2_ = null;
        } else {
          bean2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (beansBuilder_ == null) {
          beans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          beansBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.proto.CycleProto.internal_static_OuterBean_descriptor;
      }

      public org.test.proto.CycleProto.OuterBean getDefaultInstanceForType() {
        return org.test.proto.CycleProto.OuterBean.getDefaultInstance();
      }

      public org.test.proto.CycleProto.OuterBean build() {
        org.test.proto.CycleProto.OuterBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.proto.CycleProto.OuterBean buildPartial() {
        org.test.proto.CycleProto.OuterBean result = new org.test.proto.CycleProto.OuterBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          if (bean1Builder_ == null) {
            result.bean1_ = bean1_;
          } else {
            result.bean1_ = bean1Builder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          if (bean2Builder_ == null) {
            result.bean2_ = bean2_;
          } else {
            result.bean2_ = bean2Builder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (beansBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            beans_ = java.util.Collections.unmodifiableList(beans_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.beans_ = beans_;
        } else {
          result.beans_ = beansBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.proto.CycleProto.OuterBean) {
          return mergeFrom((org.test.proto.CycleProto.OuterBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.proto.CycleProto.OuterBean other) {
        if (other == org.test.proto.CycleProto.OuterBean.getDefaultInstance()) return this;
        if (other.hasBean1()) {
          mergeBean1(other.getBean1());
        }
        if (other.hasBean2()) {
          mergeBean2(other.getBean2());
        }
        if (beansBuilder_ == null) {
          if (!other.beans_.isEmpty()) {
            if (beans_.isEmpty()) {
              beans_ = other.beans_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBeansIsMutable();
              beans_.addAll(other.beans_);
            }
            onChanged();
          }
        } else {
          if (!other.beans_.isEmpty()) {
            if (beansBuilder_.isEmpty()) {
              beansBuilder_.dispose();
              beansBuilder_ = null;
              beans_ = other.beans_;
              bitField0_ = (bitField0_ & ~0x00000004);
              beansBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBeansFieldBuilder() : null;
            } else {
              beansBuilder_.addAllMessages(other.beans_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.proto.CycleProto.OuterBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.proto.CycleProto.OuterBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.test.proto.CycleProto.InnerBean bean1_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> bean1Builder_;
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public boolean hasBean1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBean getBean1() {
        if (bean1Builder_ == null) {
          return bean1_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean1_;
        } else {
          return bean1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public Builder setBean1(org.test.proto.CycleProto.InnerBean value) {
        if (bean1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bean1_ = value;
          onChanged();
        } else {
          bean1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public Builder setBean1(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (bean1Builder_ == null) {
          bean1_ = builderForValue.build();
          onChanged();
        } else {
          bean1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public Builder mergeBean1(org.test.proto.CycleProto.InnerBean value) {
        if (bean1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              bean1_ != null &&
              bean1_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            bean1_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(bean1_).mergeFrom(value).buildPartial();
          } else {
            bean1_ = value;
          }
          onChanged();
        } else {
          bean1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public Builder clearBean1() {
        if (bean1Builder_ == null) {
          bean1_ = null;
          onChanged();
        } else {
          bean1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getBean1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBean1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getBean1OrBuilder() {
        if (bean1Builder_ != null) {
          return bean1Builder_.getMessageOrBuilder();
        } else {
          return bean1_ == null ?
              org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean1_;
        }
      }
      /**
       * <code>optional .InnerBean bean1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getBean1FieldBuilder() {
        if (bean1Builder_ == null) {
          bean1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getBean1(),
                  getParentForChildren(),
                  isClean());
          bean1_ = null;
        }
        return bean1Builder_;
      }

      private org.test.proto.CycleProto.InnerBean bean2_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> bean2Builder_;
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public boolean hasBean2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBean getBean2() {
        if (bean2Builder_ == null) {
          return bean2_ == null ? org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean2_;
        } else {
          return bean2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public Builder setBean2(org.test.proto.CycleProto.InnerBean value) {
        if (bean2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bean2_ = value;
          onChanged();
        } else {
          bean2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public Builder setBean2(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (bean2Builder_ == null) {
          bean2_ = builderForValue.build();
          onChanged();
        } else {
          bean2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public Builder mergeBean2(org.test.proto.CycleProto.InnerBean value) {
        if (bean2Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              bean2_ != null &&
              bean2_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            bean2_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(bean2_).mergeFrom(value).buildPartial();
          } else {
            bean2_ = value;
          }
          onChanged();
        } else {
          bean2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public Builder clearBean2() {
        if (bean2Builder_ == null) {
          bean2_ = null;
          onChanged();
        } else {
          bean2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getBean2Builder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBean2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getBean2OrBuilder() {
        if (bean2Builder_ != null) {
          return bean2Builder_.getMessageOrBuilder();
        } else {
          return bean2_ == null ?
              org.test.proto.CycleProto.InnerBean.getDefaultInstance() : bean2_;
        }
      }
      /**
       * <code>optional .InnerBean bean2 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getBean2FieldBuilder() {
        if (bean2Builder_ == null) {
          bean2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getBean2(),
                  getParentForChildren(),
                  isClean());
          bean2_ = null;
        }
        return bean2Builder_;
      }

      private java.util.List<org.test.proto.CycleProto.InnerBean> beans_ =
        java.util.Collections.emptyList();
      private void ensureBeansIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          beans_ = new java.util.ArrayList<org.test.proto.CycleProto.InnerBean>(beans_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> beansBuilder_;

      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public java.util.List<org.test.proto.CycleProto.InnerBean> getBeansList() {
        if (beansBuilder_ == null) {
          return java.util.Collections.unmodifiableList(beans_);
        } else {
          return beansBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public int getBeansCount() {
        if (beansBuilder_ == null) {
          return beans_.size();
        } else {
          return beansBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean getBeans(int index) {
        if (beansBuilder_ == null) {
          return beans_.get(index);
        } else {
          return beansBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder setBeans(
          int index, org.test.proto.CycleProto.InnerBean value) {
        if (beansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeansIsMutable();
          beans_.set(index, value);
          onChanged();
        } else {
          beansBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder setBeans(
          int index, org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.set(index, builderForValue.build());
          onChanged();
        } else {
          beansBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder addBeans(org.test.proto.CycleProto.InnerBean value) {
        if (beansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeansIsMutable();
          beans_.add(value);
          onChanged();
        } else {
          beansBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder addBeans(
          int index, org.test.proto.CycleProto.InnerBean value) {
        if (beansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeansIsMutable();
          beans_.add(index, value);
          onChanged();
        } else {
          beansBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder addBeans(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.add(builderForValue.build());
          onChanged();
        } else {
          beansBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder addBeans(
          int index, org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.add(index, builderForValue.build());
          onChanged();
        } else {
          beansBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder addAllBeans(
          java.lang.Iterable<? extends org.test.proto.CycleProto.InnerBean> values) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, beans_);
          onChanged();
        } else {
          beansBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder clearBeans() {
        if (beansBuilder_ == null) {
          beans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          beansBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public Builder removeBeans(int index) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.remove(index);
          onChanged();
        } else {
          beansBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getBeansBuilder(
          int index) {
        return getBeansFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getBeansOrBuilder(
          int index) {
        if (beansBuilder_ == null) {
          return beans_.get(index);  } else {
          return beansBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public java.util.List<? extends org.test.proto.CycleProto.InnerBeanOrBuilder> 
           getBeansOrBuilderList() {
        if (beansBuilder_ != null) {
          return beansBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(beans_);
        }
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder addBeansBuilder() {
        return getBeansFieldBuilder().addBuilder(
            org.test.proto.CycleProto.InnerBean.getDefaultInstance());
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder addBeansBuilder(
          int index) {
        return getBeansFieldBuilder().addBuilder(
            index, org.test.proto.CycleProto.InnerBean.getDefaultInstance());
      }
      /**
       * <code>repeated .InnerBean beans = 3;</code>
       */
      public java.util.List<org.test.proto.CycleProto.InnerBean.Builder> 
           getBeansBuilderList() {
        return getBeansFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getBeansFieldBuilder() {
        if (beansBuilder_ == null) {
          beansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  beans_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          beans_ = null;
        }
        return beansBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OuterBean)
    }

    // @@protoc_insertion_point(class_scope:OuterBean)
    private static final org.test.proto.CycleProto.OuterBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.test.proto.CycleProto.OuterBean();
    }

    public static org.test.proto.CycleProto.OuterBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OuterBean>
        PARSER = new com.google.protobuf.AbstractParser<OuterBean>() {
      public OuterBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OuterBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OuterBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OuterBean> getParserForType() {
      return PARSER;
    }

    public org.test.proto.CycleProto.OuterBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InnerBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InnerBean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OuterBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OuterBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Cycle.proto\"\226\001\n\tInnerBean\022\016\n\006value1\030\001 " +
      "\001(\003\022\016\n\006value2\030\002 \001(\003\022\024\n\006value3\030\003 \001(\003:\004100" +
      "0\022\024\n\006value4\030\004 \001(\003:\0041200\022\016\n\006value5\030\005 \001(\t\022" +
      "\016\n\006value6\030\006 \001(\014\022\035\n\treference\030\007 \001(\0132\n.Inn" +
      "erBean\"\\\n\tOuterBean\022\031\n\005bean1\030\001 \001(\0132\n.Inn" +
      "erBean\022\031\n\005bean2\030\002 \001(\0132\n.InnerBean\022\031\n\005bea" +
      "ns\030\003 \003(\0132\n.InnerBeanB\036\n\016org.test.protoB\n" +
      "CycleProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InnerBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InnerBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InnerBean_descriptor,
        new java.lang.String[] { "Value1", "Value2", "Value3", "Value4", "Value5", "Value6", "Reference", });
    internal_static_OuterBean_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OuterBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OuterBean_descriptor,
        new java.lang.String[] { "Bean1", "Bean2", "Beans", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
