// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cycle.proto

package org.test.proto;

public final class CycleProto {
  private CycleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InnerBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.InnerBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 value1 = 1;</code>
     */
    boolean hasValue1();
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    long getValue1();

    /**
     * <code>optional int64 value2 = 2;</code>
     */
    boolean hasValue2();
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    long getValue2();

    /**
     * <code>optional int64 value3 = 3;</code>
     */
    boolean hasValue3();
    /**
     * <code>optional int64 value3 = 3;</code>
     */
    long getValue3();

    /**
     * <code>optional int64 value4 = 4;</code>
     */
    boolean hasValue4();
    /**
     * <code>optional int64 value4 = 4;</code>
     */
    long getValue4();

    /**
     * <code>optional string value5 = 5;</code>
     */
    boolean hasValue5();
    /**
     * <code>optional string value5 = 5;</code>
     */
    java.lang.String getValue5();
    /**
     * <code>optional string value5 = 5;</code>
     */
    com.google.protobuf.ByteString
        getValue5Bytes();

    /**
     * <code>optional .common.InnerBean reference = 6;</code>
     */
    boolean hasReference();
    /**
     * <code>optional .common.InnerBean reference = 6;</code>
     */
    org.test.proto.CycleProto.InnerBean getReference();
    /**
     * <code>optional .common.InnerBean reference = 6;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getReferenceOrBuilder();
  }
  /**
   * Protobuf type {@code common.InnerBean}
   */
  public static final class InnerBean extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.InnerBean)
      InnerBeanOrBuilder {
    // Use InnerBean.newBuilder() to construct.
    private InnerBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InnerBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InnerBean defaultInstance;
    public static InnerBean getDefaultInstance() {
      return defaultInstance;
    }

    public InnerBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InnerBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              value1_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value2_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value3_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              value4_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value5_ = bs;
              break;
            }
            case 50: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = reference_.toBuilder();
              }
              reference_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reference_);
                reference_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.proto.CycleProto.internal_static_common_InnerBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.proto.CycleProto.internal_static_common_InnerBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.proto.CycleProto.InnerBean.class, org.test.proto.CycleProto.InnerBean.Builder.class);
    }

    public static com.google.protobuf.Parser<InnerBean> PARSER =
        new com.google.protobuf.AbstractParser<InnerBean>() {
      public InnerBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InnerBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VALUE1_FIELD_NUMBER = 1;
    private long value1_;
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    public boolean hasValue1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    public long getValue1() {
      return value1_;
    }

    public static final int VALUE2_FIELD_NUMBER = 2;
    private long value2_;
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    public boolean hasValue2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    public long getValue2() {
      return value2_;
    }

    public static final int VALUE3_FIELD_NUMBER = 3;
    private long value3_;
    /**
     * <code>optional int64 value3 = 3;</code>
     */
    public boolean hasValue3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 value3 = 3;</code>
     */
    public long getValue3() {
      return value3_;
    }

    public static final int VALUE4_FIELD_NUMBER = 4;
    private long value4_;
    /**
     * <code>optional int64 value4 = 4;</code>
     */
    public boolean hasValue4() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 value4 = 4;</code>
     */
    public long getValue4() {
      return value4_;
    }

    public static final int VALUE5_FIELD_NUMBER = 5;
    private java.lang.Object value5_;
    /**
     * <code>optional string value5 = 5;</code>
     */
    public boolean hasValue5() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string value5 = 5;</code>
     */
    public java.lang.String getValue5() {
      java.lang.Object ref = value5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value5 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValue5Bytes() {
      java.lang.Object ref = value5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCE_FIELD_NUMBER = 6;
    private org.test.proto.CycleProto.InnerBean reference_;
    /**
     * <code>optional .common.InnerBean reference = 6;</code>
     */
    public boolean hasReference() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .common.InnerBean reference = 6;</code>
     */
    public org.test.proto.CycleProto.InnerBean getReference() {
      return reference_;
    }
    /**
     * <code>optional .common.InnerBean reference = 6;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getReferenceOrBuilder() {
      return reference_;
    }

    private void initFields() {
      value1_ = 0L;
      value2_ = 0L;
      value3_ = 0L;
      value4_ = 0L;
      value5_ = "";
      reference_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, value3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, value4_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getValue5Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, reference_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, value3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, value4_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getValue5Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, reference_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.test.proto.CycleProto.InnerBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.test.proto.CycleProto.InnerBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.InnerBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.InnerBean)
        org.test.proto.CycleProto.InnerBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.proto.CycleProto.internal_static_common_InnerBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.proto.CycleProto.internal_static_common_InnerBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.proto.CycleProto.InnerBean.class, org.test.proto.CycleProto.InnerBean.Builder.class);
      }

      // Construct using org.test.proto.CycleProto.InnerBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReferenceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        value2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        value3_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        value4_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        value5_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (referenceBuilder_ == null) {
          reference_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
        } else {
          referenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.proto.CycleProto.internal_static_common_InnerBean_descriptor;
      }

      public org.test.proto.CycleProto.InnerBean getDefaultInstanceForType() {
        return org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      }

      public org.test.proto.CycleProto.InnerBean build() {
        org.test.proto.CycleProto.InnerBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.proto.CycleProto.InnerBean buildPartial() {
        org.test.proto.CycleProto.InnerBean result = new org.test.proto.CycleProto.InnerBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value1_ = value1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value2_ = value2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value3_ = value3_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value4_ = value4_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value5_ = value5_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (referenceBuilder_ == null) {
          result.reference_ = reference_;
        } else {
          result.reference_ = referenceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.proto.CycleProto.InnerBean) {
          return mergeFrom((org.test.proto.CycleProto.InnerBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.proto.CycleProto.InnerBean other) {
        if (other == org.test.proto.CycleProto.InnerBean.getDefaultInstance()) return this;
        if (other.hasValue1()) {
          setValue1(other.getValue1());
        }
        if (other.hasValue2()) {
          setValue2(other.getValue2());
        }
        if (other.hasValue3()) {
          setValue3(other.getValue3());
        }
        if (other.hasValue4()) {
          setValue4(other.getValue4());
        }
        if (other.hasValue5()) {
          bitField0_ |= 0x00000010;
          value5_ = other.value5_;
          onChanged();
        }
        if (other.hasReference()) {
          mergeReference(other.getReference());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.proto.CycleProto.InnerBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.proto.CycleProto.InnerBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long value1_ ;
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public boolean hasValue1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public long getValue1() {
        return value1_;
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public Builder setValue1(long value) {
        bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public Builder clearValue1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value1_ = 0L;
        onChanged();
        return this;
      }

      private long value2_ ;
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public boolean hasValue2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public long getValue2() {
        return value2_;
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder setValue2(long value) {
        bitField0_ |= 0x00000002;
        value2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder clearValue2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value2_ = 0L;
        onChanged();
        return this;
      }

      private long value3_ ;
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public boolean hasValue3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public long getValue3() {
        return value3_;
      }
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public Builder setValue3(long value) {
        bitField0_ |= 0x00000004;
        value3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public Builder clearValue3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value3_ = 0L;
        onChanged();
        return this;
      }

      private long value4_ ;
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public boolean hasValue4() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public long getValue4() {
        return value4_;
      }
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public Builder setValue4(long value) {
        bitField0_ |= 0x00000008;
        value4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public Builder clearValue4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value4_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object value5_ = "";
      /**
       * <code>optional string value5 = 5;</code>
       */
      public boolean hasValue5() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public java.lang.String getValue5() {
        java.lang.Object ref = value5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value5_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValue5Bytes() {
        java.lang.Object ref = value5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public Builder setValue5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public Builder clearValue5() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value5_ = getDefaultInstance().getValue5();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value5 = 5;</code>
       */
      public Builder setValue5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value5_ = value;
        onChanged();
        return this;
      }

      private org.test.proto.CycleProto.InnerBean reference_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> referenceBuilder_;
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public boolean hasReference() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public org.test.proto.CycleProto.InnerBean getReference() {
        if (referenceBuilder_ == null) {
          return reference_;
        } else {
          return referenceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public Builder setReference(org.test.proto.CycleProto.InnerBean value) {
        if (referenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reference_ = value;
          onChanged();
        } else {
          referenceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public Builder setReference(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (referenceBuilder_ == null) {
          reference_ = builderForValue.build();
          onChanged();
        } else {
          referenceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public Builder mergeReference(org.test.proto.CycleProto.InnerBean value) {
        if (referenceBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              reference_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            reference_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(reference_).mergeFrom(value).buildPartial();
          } else {
            reference_ = value;
          }
          onChanged();
        } else {
          referenceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public Builder clearReference() {
        if (referenceBuilder_ == null) {
          reference_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
          onChanged();
        } else {
          referenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getReferenceBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getReferenceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getReferenceOrBuilder() {
        if (referenceBuilder_ != null) {
          return referenceBuilder_.getMessageOrBuilder();
        } else {
          return reference_;
        }
      }
      /**
       * <code>optional .common.InnerBean reference = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getReferenceFieldBuilder() {
        if (referenceBuilder_ == null) {
          referenceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getReference(),
                  getParentForChildren(),
                  isClean());
          reference_ = null;
        }
        return referenceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:common.InnerBean)
    }

    static {
      defaultInstance = new InnerBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.InnerBean)
  }

  public interface OuterBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.OuterBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .common.InnerBean bean1 = 1;</code>
     */
    boolean hasBean1();
    /**
     * <code>optional .common.InnerBean bean1 = 1;</code>
     */
    org.test.proto.CycleProto.InnerBean getBean1();
    /**
     * <code>optional .common.InnerBean bean1 = 1;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getBean1OrBuilder();

    /**
     * <code>optional .common.InnerBean bean2 = 2;</code>
     */
    boolean hasBean2();
    /**
     * <code>optional .common.InnerBean bean2 = 2;</code>
     */
    org.test.proto.CycleProto.InnerBean getBean2();
    /**
     * <code>optional .common.InnerBean bean2 = 2;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getBean2OrBuilder();

    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    java.util.List<org.test.proto.CycleProto.InnerBean> 
        getBeansList();
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    org.test.proto.CycleProto.InnerBean getBeans(int index);
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    int getBeansCount();
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    java.util.List<? extends org.test.proto.CycleProto.InnerBeanOrBuilder> 
        getBeansOrBuilderList();
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getBeansOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code common.OuterBean}
   */
  public static final class OuterBean extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.OuterBean)
      OuterBeanOrBuilder {
    // Use OuterBean.newBuilder() to construct.
    private OuterBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OuterBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OuterBean defaultInstance;
    public static OuterBean getDefaultInstance() {
      return defaultInstance;
    }

    public OuterBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OuterBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = bean1_.toBuilder();
              }
              bean1_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bean1_);
                bean1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = bean2_.toBuilder();
              }
              bean2_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bean2_);
                bean2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                beans_ = new java.util.ArrayList<org.test.proto.CycleProto.InnerBean>();
                mutable_bitField0_ |= 0x00000004;
              }
              beans_.add(input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          beans_ = java.util.Collections.unmodifiableList(beans_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.proto.CycleProto.internal_static_common_OuterBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.proto.CycleProto.internal_static_common_OuterBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.proto.CycleProto.OuterBean.class, org.test.proto.CycleProto.OuterBean.Builder.class);
    }

    public static com.google.protobuf.Parser<OuterBean> PARSER =
        new com.google.protobuf.AbstractParser<OuterBean>() {
      public OuterBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OuterBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OuterBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BEAN1_FIELD_NUMBER = 1;
    private org.test.proto.CycleProto.InnerBean bean1_;
    /**
     * <code>optional .common.InnerBean bean1 = 1;</code>
     */
    public boolean hasBean1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .common.InnerBean bean1 = 1;</code>
     */
    public org.test.proto.CycleProto.InnerBean getBean1() {
      return bean1_;
    }
    /**
     * <code>optional .common.InnerBean bean1 = 1;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getBean1OrBuilder() {
      return bean1_;
    }

    public static final int BEAN2_FIELD_NUMBER = 2;
    private org.test.proto.CycleProto.InnerBean bean2_;
    /**
     * <code>optional .common.InnerBean bean2 = 2;</code>
     */
    public boolean hasBean2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .common.InnerBean bean2 = 2;</code>
     */
    public org.test.proto.CycleProto.InnerBean getBean2() {
      return bean2_;
    }
    /**
     * <code>optional .common.InnerBean bean2 = 2;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getBean2OrBuilder() {
      return bean2_;
    }

    public static final int BEANS_FIELD_NUMBER = 3;
    private java.util.List<org.test.proto.CycleProto.InnerBean> beans_;
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    public java.util.List<org.test.proto.CycleProto.InnerBean> getBeansList() {
      return beans_;
    }
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    public java.util.List<? extends org.test.proto.CycleProto.InnerBeanOrBuilder> 
        getBeansOrBuilderList() {
      return beans_;
    }
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    public int getBeansCount() {
      return beans_.size();
    }
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    public org.test.proto.CycleProto.InnerBean getBeans(int index) {
      return beans_.get(index);
    }
    /**
     * <code>repeated .common.InnerBean beans = 3;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getBeansOrBuilder(
        int index) {
      return beans_.get(index);
    }

    private void initFields() {
      bean1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      bean2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      beans_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, bean1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, bean2_);
      }
      for (int i = 0; i < beans_.size(); i++) {
        output.writeMessage(3, beans_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bean1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bean2_);
      }
      for (int i = 0; i < beans_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, beans_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.test.proto.CycleProto.OuterBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.test.proto.CycleProto.OuterBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.OuterBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.OuterBean)
        org.test.proto.CycleProto.OuterBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.proto.CycleProto.internal_static_common_OuterBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.proto.CycleProto.internal_static_common_OuterBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.proto.CycleProto.OuterBean.class, org.test.proto.CycleProto.OuterBean.Builder.class);
      }

      // Construct using org.test.proto.CycleProto.OuterBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBean1FieldBuilder();
          getBean2FieldBuilder();
          getBeansFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (bean1Builder_ == null) {
          bean1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
        } else {
          bean1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bean2Builder_ == null) {
          bean2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
        } else {
          bean2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (beansBuilder_ == null) {
          beans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          beansBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.proto.CycleProto.internal_static_common_OuterBean_descriptor;
      }

      public org.test.proto.CycleProto.OuterBean getDefaultInstanceForType() {
        return org.test.proto.CycleProto.OuterBean.getDefaultInstance();
      }

      public org.test.proto.CycleProto.OuterBean build() {
        org.test.proto.CycleProto.OuterBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.proto.CycleProto.OuterBean buildPartial() {
        org.test.proto.CycleProto.OuterBean result = new org.test.proto.CycleProto.OuterBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (bean1Builder_ == null) {
          result.bean1_ = bean1_;
        } else {
          result.bean1_ = bean1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bean2Builder_ == null) {
          result.bean2_ = bean2_;
        } else {
          result.bean2_ = bean2Builder_.build();
        }
        if (beansBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            beans_ = java.util.Collections.unmodifiableList(beans_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.beans_ = beans_;
        } else {
          result.beans_ = beansBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.proto.CycleProto.OuterBean) {
          return mergeFrom((org.test.proto.CycleProto.OuterBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.proto.CycleProto.OuterBean other) {
        if (other == org.test.proto.CycleProto.OuterBean.getDefaultInstance()) return this;
        if (other.hasBean1()) {
          mergeBean1(other.getBean1());
        }
        if (other.hasBean2()) {
          mergeBean2(other.getBean2());
        }
        if (beansBuilder_ == null) {
          if (!other.beans_.isEmpty()) {
            if (beans_.isEmpty()) {
              beans_ = other.beans_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBeansIsMutable();
              beans_.addAll(other.beans_);
            }
            onChanged();
          }
        } else {
          if (!other.beans_.isEmpty()) {
            if (beansBuilder_.isEmpty()) {
              beansBuilder_.dispose();
              beansBuilder_ = null;
              beans_ = other.beans_;
              bitField0_ = (bitField0_ & ~0x00000004);
              beansBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBeansFieldBuilder() : null;
            } else {
              beansBuilder_.addAllMessages(other.beans_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.proto.CycleProto.OuterBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.proto.CycleProto.OuterBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.test.proto.CycleProto.InnerBean bean1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> bean1Builder_;
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public boolean hasBean1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBean getBean1() {
        if (bean1Builder_ == null) {
          return bean1_;
        } else {
          return bean1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public Builder setBean1(org.test.proto.CycleProto.InnerBean value) {
        if (bean1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bean1_ = value;
          onChanged();
        } else {
          bean1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public Builder setBean1(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (bean1Builder_ == null) {
          bean1_ = builderForValue.build();
          onChanged();
        } else {
          bean1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public Builder mergeBean1(org.test.proto.CycleProto.InnerBean value) {
        if (bean1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              bean1_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            bean1_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(bean1_).mergeFrom(value).buildPartial();
          } else {
            bean1_ = value;
          }
          onChanged();
        } else {
          bean1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public Builder clearBean1() {
        if (bean1Builder_ == null) {
          bean1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
          onChanged();
        } else {
          bean1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getBean1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBean1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getBean1OrBuilder() {
        if (bean1Builder_ != null) {
          return bean1Builder_.getMessageOrBuilder();
        } else {
          return bean1_;
        }
      }
      /**
       * <code>optional .common.InnerBean bean1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getBean1FieldBuilder() {
        if (bean1Builder_ == null) {
          bean1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getBean1(),
                  getParentForChildren(),
                  isClean());
          bean1_ = null;
        }
        return bean1Builder_;
      }

      private org.test.proto.CycleProto.InnerBean bean2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> bean2Builder_;
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public boolean hasBean2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBean getBean2() {
        if (bean2Builder_ == null) {
          return bean2_;
        } else {
          return bean2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public Builder setBean2(org.test.proto.CycleProto.InnerBean value) {
        if (bean2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bean2_ = value;
          onChanged();
        } else {
          bean2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public Builder setBean2(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (bean2Builder_ == null) {
          bean2_ = builderForValue.build();
          onChanged();
        } else {
          bean2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public Builder mergeBean2(org.test.proto.CycleProto.InnerBean value) {
        if (bean2Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              bean2_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            bean2_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(bean2_).mergeFrom(value).buildPartial();
          } else {
            bean2_ = value;
          }
          onChanged();
        } else {
          bean2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public Builder clearBean2() {
        if (bean2Builder_ == null) {
          bean2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
          onChanged();
        } else {
          bean2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getBean2Builder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBean2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getBean2OrBuilder() {
        if (bean2Builder_ != null) {
          return bean2Builder_.getMessageOrBuilder();
        } else {
          return bean2_;
        }
      }
      /**
       * <code>optional .common.InnerBean bean2 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getBean2FieldBuilder() {
        if (bean2Builder_ == null) {
          bean2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getBean2(),
                  getParentForChildren(),
                  isClean());
          bean2_ = null;
        }
        return bean2Builder_;
      }

      private java.util.List<org.test.proto.CycleProto.InnerBean> beans_ =
        java.util.Collections.emptyList();
      private void ensureBeansIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          beans_ = new java.util.ArrayList<org.test.proto.CycleProto.InnerBean>(beans_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> beansBuilder_;

      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public java.util.List<org.test.proto.CycleProto.InnerBean> getBeansList() {
        if (beansBuilder_ == null) {
          return java.util.Collections.unmodifiableList(beans_);
        } else {
          return beansBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public int getBeansCount() {
        if (beansBuilder_ == null) {
          return beans_.size();
        } else {
          return beansBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean getBeans(int index) {
        if (beansBuilder_ == null) {
          return beans_.get(index);
        } else {
          return beansBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder setBeans(
          int index, org.test.proto.CycleProto.InnerBean value) {
        if (beansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeansIsMutable();
          beans_.set(index, value);
          onChanged();
        } else {
          beansBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder setBeans(
          int index, org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.set(index, builderForValue.build());
          onChanged();
        } else {
          beansBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder addBeans(org.test.proto.CycleProto.InnerBean value) {
        if (beansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeansIsMutable();
          beans_.add(value);
          onChanged();
        } else {
          beansBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder addBeans(
          int index, org.test.proto.CycleProto.InnerBean value) {
        if (beansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeansIsMutable();
          beans_.add(index, value);
          onChanged();
        } else {
          beansBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder addBeans(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.add(builderForValue.build());
          onChanged();
        } else {
          beansBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder addBeans(
          int index, org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.add(index, builderForValue.build());
          onChanged();
        } else {
          beansBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder addAllBeans(
          java.lang.Iterable<? extends org.test.proto.CycleProto.InnerBean> values) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, beans_);
          onChanged();
        } else {
          beansBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder clearBeans() {
        if (beansBuilder_ == null) {
          beans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          beansBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public Builder removeBeans(int index) {
        if (beansBuilder_ == null) {
          ensureBeansIsMutable();
          beans_.remove(index);
          onChanged();
        } else {
          beansBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getBeansBuilder(
          int index) {
        return getBeansFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getBeansOrBuilder(
          int index) {
        if (beansBuilder_ == null) {
          return beans_.get(index);  } else {
          return beansBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public java.util.List<? extends org.test.proto.CycleProto.InnerBeanOrBuilder> 
           getBeansOrBuilderList() {
        if (beansBuilder_ != null) {
          return beansBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(beans_);
        }
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder addBeansBuilder() {
        return getBeansFieldBuilder().addBuilder(
            org.test.proto.CycleProto.InnerBean.getDefaultInstance());
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder addBeansBuilder(
          int index) {
        return getBeansFieldBuilder().addBuilder(
            index, org.test.proto.CycleProto.InnerBean.getDefaultInstance());
      }
      /**
       * <code>repeated .common.InnerBean beans = 3;</code>
       */
      public java.util.List<org.test.proto.CycleProto.InnerBean.Builder> 
           getBeansBuilderList() {
        return getBeansFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getBeansFieldBuilder() {
        if (beansBuilder_ == null) {
          beansBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  beans_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          beans_ = null;
        }
        return beansBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:common.OuterBean)
    }

    static {
      defaultInstance = new OuterBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.OuterBean)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_InnerBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_InnerBean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_OuterBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_OuterBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Cycle.proto\022\006common\"\201\001\n\tInnerBean\022\016\n\006v" +
      "alue1\030\001 \001(\003\022\016\n\006value2\030\002 \001(\003\022\016\n\006value3\030\003 " +
      "\001(\003\022\016\n\006value4\030\004 \001(\003\022\016\n\006value5\030\005 \001(\t\022$\n\tr" +
      "eference\030\006 \001(\0132\021.common.InnerBean\"q\n\tOut" +
      "erBean\022 \n\005bean1\030\001 \001(\0132\021.common.InnerBean" +
      "\022 \n\005bean2\030\002 \001(\0132\021.common.InnerBean\022 \n\005be" +
      "ans\030\003 \003(\0132\021.common.InnerBeanB\034\n\016org.test" +
      ".protoB\nCycleProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_InnerBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_InnerBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_InnerBean_descriptor,
        new java.lang.String[] { "Value1", "Value2", "Value3", "Value4", "Value5", "Reference", });
    internal_static_common_OuterBean_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_OuterBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_OuterBean_descriptor,
        new java.lang.String[] { "Bean1", "Bean2", "Beans", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
