// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CycleProto.proto

package org.test.proto;

public final class CycleProto {
  private CycleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InnerBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.InnerBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 value1 = 1;</code>
     */
    boolean hasValue1();
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    long getValue1();

    /**
     * <code>optional int64 value2 = 2;</code>
     */
    boolean hasValue2();
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    long getValue2();

    /**
     * <code>optional int64 value3 = 3;</code>
     */
    boolean hasValue3();
    /**
     * <code>optional int64 value3 = 3;</code>
     */
    long getValue3();

    /**
     * <code>optional int64 value4 = 4;</code>
     */
    boolean hasValue4();
    /**
     * <code>optional int64 value4 = 4;</code>
     */
    long getValue4();

    /**
     * <code>optional int64 value5 = 5;</code>
     */
    boolean hasValue5();
    /**
     * <code>optional int64 value5 = 5;</code>
     */
    long getValue5();
  }
  /**
   * Protobuf type {@code common.InnerBean}
   */
  public static final class InnerBean extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.InnerBean)
      InnerBeanOrBuilder {
    // Use InnerBean.newBuilder() to construct.
    private InnerBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InnerBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InnerBean defaultInstance;
    public static InnerBean getDefaultInstance() {
      return defaultInstance;
    }

    public InnerBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InnerBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              value1_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value2_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value3_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              value4_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              value5_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.proto.CycleProto.internal_static_common_InnerBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.proto.CycleProto.internal_static_common_InnerBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.proto.CycleProto.InnerBean.class, org.test.proto.CycleProto.InnerBean.Builder.class);
    }

    public static com.google.protobuf.Parser<InnerBean> PARSER =
        new com.google.protobuf.AbstractParser<InnerBean>() {
      public InnerBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InnerBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VALUE1_FIELD_NUMBER = 1;
    private long value1_;
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    public boolean hasValue1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 value1 = 1;</code>
     */
    public long getValue1() {
      return value1_;
    }

    public static final int VALUE2_FIELD_NUMBER = 2;
    private long value2_;
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    public boolean hasValue2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 value2 = 2;</code>
     */
    public long getValue2() {
      return value2_;
    }

    public static final int VALUE3_FIELD_NUMBER = 3;
    private long value3_;
    /**
     * <code>optional int64 value3 = 3;</code>
     */
    public boolean hasValue3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 value3 = 3;</code>
     */
    public long getValue3() {
      return value3_;
    }

    public static final int VALUE4_FIELD_NUMBER = 4;
    private long value4_;
    /**
     * <code>optional int64 value4 = 4;</code>
     */
    public boolean hasValue4() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 value4 = 4;</code>
     */
    public long getValue4() {
      return value4_;
    }

    public static final int VALUE5_FIELD_NUMBER = 5;
    private long value5_;
    /**
     * <code>optional int64 value5 = 5;</code>
     */
    public boolean hasValue5() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 value5 = 5;</code>
     */
    public long getValue5() {
      return value5_;
    }

    private void initFields() {
      value1_ = 0L;
      value2_ = 0L;
      value3_ = 0L;
      value4_ = 0L;
      value5_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, value3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, value4_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, value5_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, value3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, value4_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, value5_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.test.proto.CycleProto.InnerBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.InnerBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.test.proto.CycleProto.InnerBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.InnerBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.InnerBean)
        org.test.proto.CycleProto.InnerBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.proto.CycleProto.internal_static_common_InnerBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.proto.CycleProto.internal_static_common_InnerBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.proto.CycleProto.InnerBean.class, org.test.proto.CycleProto.InnerBean.Builder.class);
      }

      // Construct using org.test.proto.CycleProto.InnerBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        value2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        value3_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        value4_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        value5_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.proto.CycleProto.internal_static_common_InnerBean_descriptor;
      }

      public org.test.proto.CycleProto.InnerBean getDefaultInstanceForType() {
        return org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      }

      public org.test.proto.CycleProto.InnerBean build() {
        org.test.proto.CycleProto.InnerBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.proto.CycleProto.InnerBean buildPartial() {
        org.test.proto.CycleProto.InnerBean result = new org.test.proto.CycleProto.InnerBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value1_ = value1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value2_ = value2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value3_ = value3_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value4_ = value4_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value5_ = value5_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.proto.CycleProto.InnerBean) {
          return mergeFrom((org.test.proto.CycleProto.InnerBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.proto.CycleProto.InnerBean other) {
        if (other == org.test.proto.CycleProto.InnerBean.getDefaultInstance()) return this;
        if (other.hasValue1()) {
          setValue1(other.getValue1());
        }
        if (other.hasValue2()) {
          setValue2(other.getValue2());
        }
        if (other.hasValue3()) {
          setValue3(other.getValue3());
        }
        if (other.hasValue4()) {
          setValue4(other.getValue4());
        }
        if (other.hasValue5()) {
          setValue5(other.getValue5());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.proto.CycleProto.InnerBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.proto.CycleProto.InnerBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long value1_ ;
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public boolean hasValue1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public long getValue1() {
        return value1_;
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public Builder setValue1(long value) {
        bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value1 = 1;</code>
       */
      public Builder clearValue1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value1_ = 0L;
        onChanged();
        return this;
      }

      private long value2_ ;
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public boolean hasValue2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public long getValue2() {
        return value2_;
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder setValue2(long value) {
        bitField0_ |= 0x00000002;
        value2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder clearValue2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value2_ = 0L;
        onChanged();
        return this;
      }

      private long value3_ ;
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public boolean hasValue3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public long getValue3() {
        return value3_;
      }
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public Builder setValue3(long value) {
        bitField0_ |= 0x00000004;
        value3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value3 = 3;</code>
       */
      public Builder clearValue3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value3_ = 0L;
        onChanged();
        return this;
      }

      private long value4_ ;
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public boolean hasValue4() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public long getValue4() {
        return value4_;
      }
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public Builder setValue4(long value) {
        bitField0_ |= 0x00000008;
        value4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value4 = 4;</code>
       */
      public Builder clearValue4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value4_ = 0L;
        onChanged();
        return this;
      }

      private long value5_ ;
      /**
       * <code>optional int64 value5 = 5;</code>
       */
      public boolean hasValue5() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 value5 = 5;</code>
       */
      public long getValue5() {
        return value5_;
      }
      /**
       * <code>optional int64 value5 = 5;</code>
       */
      public Builder setValue5(long value) {
        bitField0_ |= 0x00000010;
        value5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 value5 = 5;</code>
       */
      public Builder clearValue5() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value5_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.InnerBean)
    }

    static {
      defaultInstance = new InnerBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.InnerBean)
  }

  public interface OuterBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.OuterBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .common.InnerBean value1 = 1;</code>
     */
    boolean hasValue1();
    /**
     * <code>optional .common.InnerBean value1 = 1;</code>
     */
    org.test.proto.CycleProto.InnerBean getValue1();
    /**
     * <code>optional .common.InnerBean value1 = 1;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getValue1OrBuilder();

    /**
     * <code>optional .common.InnerBean value2 = 2;</code>
     */
    boolean hasValue2();
    /**
     * <code>optional .common.InnerBean value2 = 2;</code>
     */
    org.test.proto.CycleProto.InnerBean getValue2();
    /**
     * <code>optional .common.InnerBean value2 = 2;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getValue2OrBuilder();

    /**
     * <code>optional .common.InnerBean value3 = 3;</code>
     */
    boolean hasValue3();
    /**
     * <code>optional .common.InnerBean value3 = 3;</code>
     */
    org.test.proto.CycleProto.InnerBean getValue3();
    /**
     * <code>optional .common.InnerBean value3 = 3;</code>
     */
    org.test.proto.CycleProto.InnerBeanOrBuilder getValue3OrBuilder();
  }
  /**
   * Protobuf type {@code common.OuterBean}
   */
  public static final class OuterBean extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.OuterBean)
      OuterBeanOrBuilder {
    // Use OuterBean.newBuilder() to construct.
    private OuterBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OuterBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OuterBean defaultInstance;
    public static OuterBean getDefaultInstance() {
      return defaultInstance;
    }

    public OuterBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OuterBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = value1_.toBuilder();
              }
              value1_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(value1_);
                value1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = value2_.toBuilder();
              }
              value2_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(value2_);
                value2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              org.test.proto.CycleProto.InnerBean.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = value3_.toBuilder();
              }
              value3_ = input.readMessage(org.test.proto.CycleProto.InnerBean.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(value3_);
                value3_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.proto.CycleProto.internal_static_common_OuterBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.proto.CycleProto.internal_static_common_OuterBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.proto.CycleProto.OuterBean.class, org.test.proto.CycleProto.OuterBean.Builder.class);
    }

    public static com.google.protobuf.Parser<OuterBean> PARSER =
        new com.google.protobuf.AbstractParser<OuterBean>() {
      public OuterBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OuterBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OuterBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VALUE1_FIELD_NUMBER = 1;
    private org.test.proto.CycleProto.InnerBean value1_;
    /**
     * <code>optional .common.InnerBean value1 = 1;</code>
     */
    public boolean hasValue1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .common.InnerBean value1 = 1;</code>
     */
    public org.test.proto.CycleProto.InnerBean getValue1() {
      return value1_;
    }
    /**
     * <code>optional .common.InnerBean value1 = 1;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getValue1OrBuilder() {
      return value1_;
    }

    public static final int VALUE2_FIELD_NUMBER = 2;
    private org.test.proto.CycleProto.InnerBean value2_;
    /**
     * <code>optional .common.InnerBean value2 = 2;</code>
     */
    public boolean hasValue2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .common.InnerBean value2 = 2;</code>
     */
    public org.test.proto.CycleProto.InnerBean getValue2() {
      return value2_;
    }
    /**
     * <code>optional .common.InnerBean value2 = 2;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getValue2OrBuilder() {
      return value2_;
    }

    public static final int VALUE3_FIELD_NUMBER = 3;
    private org.test.proto.CycleProto.InnerBean value3_;
    /**
     * <code>optional .common.InnerBean value3 = 3;</code>
     */
    public boolean hasValue3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .common.InnerBean value3 = 3;</code>
     */
    public org.test.proto.CycleProto.InnerBean getValue3() {
      return value3_;
    }
    /**
     * <code>optional .common.InnerBean value3 = 3;</code>
     */
    public org.test.proto.CycleProto.InnerBeanOrBuilder getValue3OrBuilder() {
      return value3_;
    }

    private void initFields() {
      value1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      value2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      value3_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, value3_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, value3_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.test.proto.CycleProto.OuterBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.proto.CycleProto.OuterBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.test.proto.CycleProto.OuterBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.OuterBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.OuterBean)
        org.test.proto.CycleProto.OuterBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.proto.CycleProto.internal_static_common_OuterBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.proto.CycleProto.internal_static_common_OuterBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.proto.CycleProto.OuterBean.class, org.test.proto.CycleProto.OuterBean.Builder.class);
      }

      // Construct using org.test.proto.CycleProto.OuterBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValue1FieldBuilder();
          getValue2FieldBuilder();
          getValue3FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (value1Builder_ == null) {
          value1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
        } else {
          value1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (value2Builder_ == null) {
          value2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
        } else {
          value2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (value3Builder_ == null) {
          value3_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
        } else {
          value3Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.proto.CycleProto.internal_static_common_OuterBean_descriptor;
      }

      public org.test.proto.CycleProto.OuterBean getDefaultInstanceForType() {
        return org.test.proto.CycleProto.OuterBean.getDefaultInstance();
      }

      public org.test.proto.CycleProto.OuterBean build() {
        org.test.proto.CycleProto.OuterBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.proto.CycleProto.OuterBean buildPartial() {
        org.test.proto.CycleProto.OuterBean result = new org.test.proto.CycleProto.OuterBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (value1Builder_ == null) {
          result.value1_ = value1_;
        } else {
          result.value1_ = value1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (value2Builder_ == null) {
          result.value2_ = value2_;
        } else {
          result.value2_ = value2Builder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (value3Builder_ == null) {
          result.value3_ = value3_;
        } else {
          result.value3_ = value3Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.proto.CycleProto.OuterBean) {
          return mergeFrom((org.test.proto.CycleProto.OuterBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.proto.CycleProto.OuterBean other) {
        if (other == org.test.proto.CycleProto.OuterBean.getDefaultInstance()) return this;
        if (other.hasValue1()) {
          mergeValue1(other.getValue1());
        }
        if (other.hasValue2()) {
          mergeValue2(other.getValue2());
        }
        if (other.hasValue3()) {
          mergeValue3(other.getValue3());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.proto.CycleProto.OuterBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.proto.CycleProto.OuterBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.test.proto.CycleProto.InnerBean value1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> value1Builder_;
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public boolean hasValue1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBean getValue1() {
        if (value1Builder_ == null) {
          return value1_;
        } else {
          return value1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public Builder setValue1(org.test.proto.CycleProto.InnerBean value) {
        if (value1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value1_ = value;
          onChanged();
        } else {
          value1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public Builder setValue1(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (value1Builder_ == null) {
          value1_ = builderForValue.build();
          onChanged();
        } else {
          value1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public Builder mergeValue1(org.test.proto.CycleProto.InnerBean value) {
        if (value1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              value1_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            value1_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(value1_).mergeFrom(value).buildPartial();
          } else {
            value1_ = value;
          }
          onChanged();
        } else {
          value1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public Builder clearValue1() {
        if (value1Builder_ == null) {
          value1_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
          onChanged();
        } else {
          value1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getValue1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getValue1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getValue1OrBuilder() {
        if (value1Builder_ != null) {
          return value1Builder_.getMessageOrBuilder();
        } else {
          return value1_;
        }
      }
      /**
       * <code>optional .common.InnerBean value1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getValue1FieldBuilder() {
        if (value1Builder_ == null) {
          value1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getValue1(),
                  getParentForChildren(),
                  isClean());
          value1_ = null;
        }
        return value1Builder_;
      }

      private org.test.proto.CycleProto.InnerBean value2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> value2Builder_;
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public boolean hasValue2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBean getValue2() {
        if (value2Builder_ == null) {
          return value2_;
        } else {
          return value2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public Builder setValue2(org.test.proto.CycleProto.InnerBean value) {
        if (value2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value2_ = value;
          onChanged();
        } else {
          value2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public Builder setValue2(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (value2Builder_ == null) {
          value2_ = builderForValue.build();
          onChanged();
        } else {
          value2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public Builder mergeValue2(org.test.proto.CycleProto.InnerBean value) {
        if (value2Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              value2_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            value2_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(value2_).mergeFrom(value).buildPartial();
          } else {
            value2_ = value;
          }
          onChanged();
        } else {
          value2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public Builder clearValue2() {
        if (value2Builder_ == null) {
          value2_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
          onChanged();
        } else {
          value2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getValue2Builder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getValue2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getValue2OrBuilder() {
        if (value2Builder_ != null) {
          return value2Builder_.getMessageOrBuilder();
        } else {
          return value2_;
        }
      }
      /**
       * <code>optional .common.InnerBean value2 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getValue2FieldBuilder() {
        if (value2Builder_ == null) {
          value2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getValue2(),
                  getParentForChildren(),
                  isClean());
          value2_ = null;
        }
        return value2Builder_;
      }

      private org.test.proto.CycleProto.InnerBean value3_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> value3Builder_;
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public boolean hasValue3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean getValue3() {
        if (value3Builder_ == null) {
          return value3_;
        } else {
          return value3Builder_.getMessage();
        }
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public Builder setValue3(org.test.proto.CycleProto.InnerBean value) {
        if (value3Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value3_ = value;
          onChanged();
        } else {
          value3Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public Builder setValue3(
          org.test.proto.CycleProto.InnerBean.Builder builderForValue) {
        if (value3Builder_ == null) {
          value3_ = builderForValue.build();
          onChanged();
        } else {
          value3Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public Builder mergeValue3(org.test.proto.CycleProto.InnerBean value) {
        if (value3Builder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              value3_ != org.test.proto.CycleProto.InnerBean.getDefaultInstance()) {
            value3_ =
              org.test.proto.CycleProto.InnerBean.newBuilder(value3_).mergeFrom(value).buildPartial();
          } else {
            value3_ = value;
          }
          onChanged();
        } else {
          value3Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public Builder clearValue3() {
        if (value3Builder_ == null) {
          value3_ = org.test.proto.CycleProto.InnerBean.getDefaultInstance();
          onChanged();
        } else {
          value3Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBean.Builder getValue3Builder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getValue3FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      public org.test.proto.CycleProto.InnerBeanOrBuilder getValue3OrBuilder() {
        if (value3Builder_ != null) {
          return value3Builder_.getMessageOrBuilder();
        } else {
          return value3_;
        }
      }
      /**
       * <code>optional .common.InnerBean value3 = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder> 
          getValue3FieldBuilder() {
        if (value3Builder_ == null) {
          value3Builder_ = new com.google.protobuf.SingleFieldBuilder<
              org.test.proto.CycleProto.InnerBean, org.test.proto.CycleProto.InnerBean.Builder, org.test.proto.CycleProto.InnerBeanOrBuilder>(
                  getValue3(),
                  getParentForChildren(),
                  isClean());
          value3_ = null;
        }
        return value3Builder_;
      }

      // @@protoc_insertion_point(builder_scope:common.OuterBean)
    }

    static {
      defaultInstance = new OuterBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.OuterBean)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_InnerBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_InnerBean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_OuterBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_OuterBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020CycleProto.proto\022\006common\"[\n\tInnerBean\022" +
      "\016\n\006value1\030\001 \001(\003\022\016\n\006value2\030\002 \001(\003\022\016\n\006value" +
      "3\030\003 \001(\003\022\016\n\006value4\030\004 \001(\003\022\016\n\006value5\030\005 \001(\003\"" +
      "t\n\tOuterBean\022!\n\006value1\030\001 \001(\0132\021.common.In" +
      "nerBean\022!\n\006value2\030\002 \001(\0132\021.common.InnerBe" +
      "an\022!\n\006value3\030\003 \001(\0132\021.common.InnerBeanB\020\n" +
      "\016org.test.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_InnerBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_InnerBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_InnerBean_descriptor,
        new java.lang.String[] { "Value1", "Value2", "Value3", "Value4", "Value5", });
    internal_static_common_OuterBean_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_OuterBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_OuterBean_descriptor,
        new java.lang.String[] { "Value1", "Value2", "Value3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
